<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1ffa8838-e4fa-4711-a075-22efc31011b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Back to equipment page&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[3]/div/div/div/div[1]/section[1]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAYAAAD9lDaoAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMS8yMS8xNzEDfK0AAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzbovLKMAAAA40lEQVQokW3RIUtDURgG4Gd3YcGggjCDCDvBoEUFm39CFi5LNoNxGiz+Bi02iyYPWAymVYvFXzAuK8KC2Eyyey1nY5v3tHN4eD/O+zWqqlJ3QiyP8YBOow6FWO7jBVsY/UMhlkd4xja+cJItgV3cp4RvnBZ59jZLCrHcwTvWMMJZkWcDyBLYQ8QqfucBNDpPkxUM0cY4jZiBadIhNtP9ZhlM0Q8+UeEqxLIXYtlcQEWefaCXRq7jEZfzaP53bbziAJPUVb/Is/FCmSGWG7hDNz0N0K1rvIULXKOFYe3uEj7HLZp/5FRaBHR2DE4AAAAASUVORK5CYII=' and @alt = 'Back to equipment page']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAYAAAD9lDaoAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMS8yMS8xNzEDfK0AAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzbovLKMAAAA40lEQVQokW3RIUtDURgG4Gd3YcGggjCDCDvBoEUFm39CFi5LNoNxGiz+Bi02iyYPWAymVYvFXzAuK8KC2Eyyey1nY5v3tHN4eD/O+zWqqlJ3QiyP8YBOow6FWO7jBVsY/UMhlkd4xja+cJItgV3cp4RvnBZ59jZLCrHcwTvWMMJZkWcDyBLYQ8QqfucBNDpPkxUM0cY4jZiBadIhNtP9ZhlM0Q8+UeEqxLIXYtlcQEWefaCXRq7jEZfzaP53bbziAJPUVb/Is/FCmSGWG7hDNz0N0K1rvIULXKOFYe3uEj7HLZp/5FRaBHR2DE4AAAAASUVORK5CYII=</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Back to equipment page</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;equipment-section no-padding&quot;]/div[@class=&quot;well well-as-card&quot;]/section[@class=&quot;equipment-breadcrumbs z-top&quot;]/div[@class=&quot;back pointer&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/section/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Back to equipment page']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/section/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAYAAAD9lDaoAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMS8yMS8xNzEDfK0AAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzbovLKMAAAA40lEQVQokW3RIUtDURgG4Gd3YcGggjCDCDvBoEUFm39CFi5LNoNxGiz+Bi02iyYPWAymVYvFXzAuK8KC2Eyyey1nY5v3tHN4eD/O+zWqqlJ3QiyP8YBOow6FWO7jBVsY/UMhlkd4xja+cJItgV3cp4RvnBZ59jZLCrHcwTvWMMJZkWcDyBLYQ8QqfucBNDpPkxUM0cY4jZiBadIhNtP9ZhlM0Q8+UeEqxLIXYtlcQEWefaCXRq7jEZfzaP53bbziAJPUVb/Is/FCmSGWG7hDNz0N0K1rvIULXKOFYe3uEj7HLZp/5FRaBHR2DE4AAAAASUVORK5CYII=')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/section/a/img</value>
   </webElementXpaths>
</WebElementEntity>
